In [19]:
# Initial Setup for Notebook
import pathlib, data_conduit
from data_conduit.qc import qc_datastructure, plot_path_grid

from movement.plots import plot_centroid_trajectory
from data_conduit.qc.slicing import slice_pose_for_trial
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import xarray as xr

# Anchor to the repo root so ROOT resolves regardless of the notebook's working dir.
REPO = pathlib.Path(data_conduit.__file__).resolve().parents[2]
ROOT = REPO / 'datasets/firstdata/BonsaiFiles'

In [2]:
# Extract the data using the qc_datastructure function, which will build a catalog of the data files in the specified directory.

datastructure = qc_datastructure(
    root = ROOT,
    depth = 2,                                                                          # Specify the number of levels levels beneath root that the session folders sit.
    level_names = ('mouseID', 'day'),                                                   # Specify the hierarchical levels for the data structure in the directory. ie., the first level is 'mouseID' and the second level is 'day'.
    streams=('events', 'nosepoke', 'soundcard', 'session_settings', 'video', 'dlc'),    # Specify the data streams to include in the catalog. Options include 'events', 'nosepoke', 'soundcard', 'session_settings', 'video', and 'dlc'.
    # include=None,                                                                       # Specify any specific files or folders to include in the catalog. If None, all files and folders are included. Only applies to directory level specified by depth. For example, if depth=2, then include will only apply to the second level of the directory structure.
    # exclude=None,                                                                       # Specify any specific files or folders to exclude from the catalog. If None, no files or folders are excluded. Only applies to directory level specified by depth. For example, if depth=2, then exclude will only apply to the second level of the directory structure.
    #device_yaml = './device.yml',                                                     # Specify the path to the device configuration YAML file. This file contains information about the devices used in the experiment, such as their names and types.
    #soundcard_yaml = './soundcard.yml',                                               # Specify the path to the soundcard configuration YAML file. This file contains information about the soundcards used in the experiment, such as their names and types.     
    #nosepoke_count = 18,                                                               # Specify the number of nosepoke ports in the experiment. This is used to validate the nosepoke data and ensure that it matches the expected number of ports.
    #trial_start_buffer = 0.0                                                            
    # l0_selector = None,                                                                 # L0 selectors will apply to mouseID here
    # l1_selector = None,                                                                 # L1 selectors will apply to day here
    # l2_selector = None,                                                                 # L2 selectors will apply to session here.
)

datastructure.load() # Load the data structure into memory, making it ready for use.

datastructure

                  Warning: verbose output disabled for ExperimentEvents.
                  If any files/paths are missing or invalid for the monosource_data_arrays you specified,
                  you may not see warnings about them. Set verbose=True to enable warnings.


                  Warning: verbose output disabled for SoundCard.
                  If any files/paths are missing or invalid for the monosource_data_arrays you specified,
                  you may not see warnings about them. Set verbose=True to enable warnings.


                  Warning: verbose output disabled for SessionSettings.
                  If any files/paths are missing or invalid for the monosource_data_arrays you specified,
                  you may not see warnings about them. Set verbose=True to enable warnings.

2026-07-03 15:56:29.663 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-26T18-47-11': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 1/2026-03-26T18-47-11.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:29.787 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-07T16-18-09': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 10/2026-04-07T16-18-09.
  objects = self.catalog.read_session(info['path'])

                  Warning: verbose output disabled for VideoData.
                  If any files/paths are missing or invalid for the monosource_data_arrays you specified,
                  you may not see warnings about them. Set verbose=True to enable warnings.

2026-07-03 15:56:29.949 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-07T16-25-44': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 10/2026-04-07T16-25-44.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:30.143 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-07T16-38-36': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 10/2026-04-07T16-38-36.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:30.270 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-07T16-46-00': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 10/2026-04-07T16-46-00.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:30.475 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-08T15-43-23': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 11/2026-04-08T15-43-23.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:30.604 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-08T15-54-59': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 11/2026-04-08T15-54-59.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:30.730 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-08T15-58-43': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 11/2026-04-08T15-58-43.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:30.843 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-08T16-03-03': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 11/2026-04-08T16-03-03.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:30.968 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-08T16-07-24': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 11/2026-04-08T16-07-24.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:31.386 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-10T14-29-59': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 12/2026-04-10T14-29-59.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:31.504 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-10T14-36-58': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 12/2026-04-10T14-36-58.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:31.615 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-10T14-39-01': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 12/2026-04-10T14-39-01.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:31.788 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-10T14-43-14': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 12/2026-04-10T14-43-14.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:31.907 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-10T14-47-10': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 12/2026-04-10T14-47-10.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:32.036 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-10T14-51-28': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 12/2026-04-10T14-51-28.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:32.236 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-11T16-31-44': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 13/2026-04-11T16-31-44.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:32.357 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-11T16-43-21': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 13/2026-04-11T16-43-21.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:32.465 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-11T16-45-45': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 13/2026-04-11T16-45-45.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:32.597 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-11T16-48-26': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 13/2026-04-11T16-48-26.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:32.764 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T152615Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T152615Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:32.875 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T152936Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T152936Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:32.980 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T153220Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T153220Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:33.086 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T153501Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T153501Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:33.182 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T153647Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T153647Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:33.273 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T153742Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T153742Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:33.371 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T153909Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T153909Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:33.472 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T154403Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T154403Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:33.584 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T154919Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T154919Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:33.690 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-15T155631Z': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 14/2026-04-15T155631Z.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:33.898 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-27T19-21-42': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 2/2026-03-27T19-21-42.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:34.014 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-27T19-43-08': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 2/2026-03-27T19-43-08.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:34.269 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-27T19-52-12': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 2/2026-03-27T19-52-12.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:34.485 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-30T13-52-35': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 3/2026-03-30T13-52-35.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:34.644 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-30T14-06-24': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 3/2026-03-30T14-06-24.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:34.758 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-30T14-10-06': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 3/2026-03-30T14-10-06.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:34.927 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-30T14-13-52': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 3/2026-03-30T14-13-52.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:35.034 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-30T14-16-19': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 3/2026-03-30T14-16-19.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:35.145 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-30T14-18-47': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 3/2026-03-30T14-18-47.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:35.286 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-30T14-22-45': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 3/2026-03-30T14-22-45.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:35.488 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-31T16-30-24': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 4/2026-03-31T16-30-24.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:35.614 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-31T16-37-00': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 4/2026-03-31T16-37-00.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:35.732 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-31T16-40-43': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 4/2026-03-31T16-40-43.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:35.960 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-03-31T16-45-41': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 4/2026-03-31T16-45-41.
  objects = self.catalog.read_session(info['path'])

2026-07-03 15:56:36.099 | WARNING  | data_conduit.datastructure:read_session:236 - /home/callum/Keshavarzi-Lab-Workspace/data-conduit/src/data_conduit/datastructure.py:551: UserWarning: reader 'dlc' skipped for session '2026-04-01T11-20-09': FileNotFoundError: no 'DLC' folder in session /home/callum/Keshavarzi-Lab-Workspace/data-conduit/datasets/firstdata/BonsaiFiles/FLR_M01569521/Day 5/2026-04-01T11-20-09.
  objects = self.catalog.read_session(info['path'])


In [23]:
print("Loaded streams:\n============================================")
for stream in datastructure:
    print(f'    ID| {stream}\n    ======================')
    display(datastructure[stream].to_dataframe().head() if hasattr(datastructure[stream], 'to_dataframe') else datastructure[stream].head())
    print(f'Total entries: {len(datastructure[stream])}\n\n')

Loaded streams:
============================================
    ID| nosepoke:Activations
    ======================

Empty DataFrame
Columns: [device, register, localID, session, mouseID, day, Activations_data]
Index: []

Total entries: 0


    ID| nosepoke:LEDs
    ======================

Empty DataFrame
Columns: [device, register, localID, session, mouseID, day, LEDs_data]
Index: []

Total entries: 0


    ID| nosepoke:Valves
    ======================

Empty DataFrame
Columns: [device, register, localID, session, mouseID, day, Valves_data]
Index: []

Total entries: 0


    ID| nosepoke:Rewards
    ======================

Empty DataFrame
Columns: [device, register, localID, session, mouseID, day, Rewards_data]
Index: []

Total entries: 0


    ID| session_settings:metadata
    ======================

,arenaCenter,innerRingRadius,innerRingDistance,outerRingRadius,nosepokeDistance,overlayLayerOn,screenDivisions,actuatorRateLimit,loggingRootPath,nosepokeRotationTolerance,...,ringHomingCommand,syncPulseLimits,animalId,nosepokeHomingCommand.position,nosepokeHomingCommand.acceleration,nosepokeHomingCommand.deceleration,nosepokeHomingCommand.velocity,session,mouseID,day
0,"[385, 272]",166.0,50.0,245.0,50.0,10,30,0.2,C:\Users\Keshavarzi lab\LogData\PathIntegratio...,0.1,...,"[{'position': 0.0, 'acceleration': 200.0, 'dec...","[0.5, 3.0]",FLR_M01569521,0.0,200.0,200.0,5.0,2026-03-26T18-47-11,FLR_M01569521,Day 1
1,"[385, 272]",166.0,50.0,245.0,50.0,10,30,0.2,C:\Users\Keshavarzi lab\LogData\PathIntegratio...,0.1,...,"[{'position': 0.0, 'acceleration': 200.0, 'dec...","[0.5, 3.0]",FLR_M01569521,0.0,200.0,200.0,5.0,2026-04-07T16-18-09,FLR_M01569521,Day 10
2,"[385, 272]",166.0,50.0,245.0,50.0,10,30,0.2,C:\Users\Keshavarzi lab\LogData\PathIntegratio...,0.1,...,"[{'position': 0.0, 'acceleration': 200.0, 'dec...","[0.5, 3.0]",FLR_M01569521,0.0,200.0,200.0,5.0,2026-04-07T16-25-44,FLR_M01569521,Day 10
3,"[385, 272]",166.0,50.0,245.0,50.0,10,30,0.2,C:\Users\Keshavarzi lab\LogData\PathIntegratio...,0.1,...,"[{'position': 0.0, 'acceleration': 200.0, 'dec...","[0.5, 3.0]",FLR_M01569521,0.0,200.0,200.0,5.0,2026-04-07T16-38-36,FLR_M01569521,Day 10
4,"[385, 272]",166.0,50.0,245.0,50.0,10,30,0.2,C:\Users\Keshavarzi lab\LogData\PathIntegratio...,0.1,...,"[{'position': 0.0, 'acceleration': 200.0, 'dec...","[0.5, 3.0]",FLR_M01569521,0.0,200.0,200.0,5.0,2026-04-07T16-46-00,FLR_M01569521,Day 10

Total entries: 290


    ID| session_settings:trials
    ======================

,trial,maxRuntime,odorScramble,rewardTimeout,rewardPortIndicators,overlayAlpha,seconds,landmark.useOffsetAsOverride,landmark.draw,landmark.yLocation,...,odorScramble.accelerationRing,odorScramble.decelerationRing,odorScramble.velocityRing,odorScramble.rotationRangesNP_0,odorScramble.rotationRangesNP_1,odorScramble.rotationRangesRing_0,odorScramble.rotationRangesRing_1,session,mouseID,day
0,trial_1,120.0,None,6000.0,True,1.0,25381.92,True,False,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-26T18-47-11,FLR_M01569521,Day 1
1,trial_2,120.0,None,6000.0,True,1.0,25381.92,True,False,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-26T18-47-11,FLR_M01569521,Day 1
2,trial_3,120.0,None,6000.0,True,1.0,25381.92,True,False,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-26T18-47-11,FLR_M01569521,Day 1
3,trial_4,120.0,None,6000.0,True,1.0,25381.92,True,False,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-26T18-47-11,FLR_M01569521,Day 1
4,trial_5,120.0,None,6000.0,True,1.0,25381.92,True,False,0.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-03-26T18-47-11,FLR_M01569521,Day 1

Total entries: 28185


    ID| video
    ======================

   FrameID        Timestamp              session        mouseID    day
0  5458953  454223541621192  2026-03-26T18-47-11  FLR_M01569521  Day 1
1  5458954  454223558286536  2026-03-26T18-47-11  FLR_M01569521  Day 1
2  5458955  454223574953136  2026-03-26T18-47-11  FLR_M01569521  Day 1
3  5458956  454223591618864  2026-03-26T18-47-11  FLR_M01569521  Day 1
4  5458957  454223608281864  2026-03-26T18-47-11  FLR_M01569521  Day 1

Total entries: 6901079


    ID| trials
    ======================

,trial_index,start_time,end_time,tz_triggered_time,outbound_start_time,outbound_end_time,inbound_start_time,inbound_end_time,TTT,TTP,ChosenPort,CorrectPort,outcome,LED,angle_offset,target_zone_size,session,mouseID,day
0,1,25399.488000,25534.672480,25423.814976,25399.488000,25423.814976,25423.814976,25534.672480,24.326976,110.857504,3,0,Success,OFF,60.0,245.0,2026-03-26T18-47-11,FLR_M01569521,Day 1
1,2,25534.672480,25543.792000,25540.960992,25534.672480,25540.960992,25540.960992,25543.792000,6.288512,2.831008,3,0,Success,OFF,60.0,245.0,2026-03-26T18-47-11,FLR_M01569521,Day 1
2,3,25543.792000,25551.266976,25550.009984,25543.792000,25550.009984,25550.009984,25551.266976,6.217984,1.256992,3,0,Success,OFF,60.0,245.0,2026-03-26T18-47-11,FLR_M01569521,Day 1
3,4,25551.266976,25599.368000,25560.493984,25551.266976,25560.493984,25560.493984,25599.368000,9.227008,38.874016,14,0,Success,OFF,60.0,245.0,2026-03-26T18-47-11,FLR_M01569521,Day 1
4,5,25599.368000,25629.428000,25610.774976,25599.368000,25610.774976,25610.774976,25629.428000,11.406976,18.653024,14,0,Success,OFF,-80.0,245.0,2026-03-26T18-47-11,FLR_M01569521,Day 1

Total entries: 7804


    ID| dlc:position
    ======================

                                          session        mouseID     day  \
Time         keypoints space
15994.716576 nose      x      2026-04-08T16-14-45  FLR_M01569521  Day 11
                       y      2026-04-08T16-14-45  FLR_M01569521  Day 11
             lear      x      2026-04-08T16-14-45  FLR_M01569521  Day 11
                       y      2026-04-08T16-14-45  FLR_M01569521  Day 11
             rear      x      2026-04-08T16-14-45  FLR_M01569521  Day 11

                                position
Time         keypoints space
15994.716576 nose      x      555.145940
                       y       87.111534
             lear      x      548.847800
                       y       94.448814
             rear      x      556.936500

Total entries: 417980


    ID| dlc:confidence
    ======================

                                    session        mouseID     day  confidence
Time         keypoints
15994.716576 nose       2026-04-08T16-14-45  FLR_M01569521  Day 11         1.0
             lear       2026-04-08T16-14-45  FLR_M01569521  Day 11         1.0
             rear       2026-04-08T16-14-45  FLR_M01569521  Day 11         1.0
             body       2026-04-08T16-14-45  FLR_M01569521  Day 11         1.0
             tailbase   2026-04-08T16-14-45  FLR_M01569521  Day 11         1.0

Total entries: 417980

In [22]:
datastructure['nosepoke:Activations']

<xarray.DataArray 'Activations_data' (Time: 0, peripherals: 18)> Size: 0B

Coordinates:
  * Time         (Time) float64 0B
    session      (Time) <U40 0B
    mouseID      (Time) object 0B
    day          (Time) object 0B
  * peripherals  (peripherals) <U5 360B 'NP_0' 'NP_1' 'NP_2' ... 'NP_16' 'NP_17'
    device       (peripherals) <U9 648B 'Behavior0' 'Behavior0' ... 'Behavior5'
    register     (peripherals) <U2 144B '32' '32' '32' '32' ... '32' '32' '32'
    localID      (peripherals) <U7 504B 'DIPort0' 'DIPort1' ... 'DIPort2'
Attributes:
    description:        Base DataArray for unified coordinates of type Activa...
    source:             Constructed using construct_base_da function
    _lookup_array_ref:  <xarray.DataArray 'Activations_lookup' (peripherals: ...

# Filtering| Must first filter trials according to `./data-conduit/src/data_conduit/qc/Training-trials_detail.xlsx` provided by Celia. 

'''
for most of the animal we need to include all trials from a given trials to the end.

For the 2 last animals, the protocol is divided in 4 blocks starting with 1 trial ON, followed by 25 or 20 trials OFF.
For these 2, in addition to select the trials from trial X to the last trial, we have to delete the remaining ON trials in the middle of the session.
'''

Numbers beneath each mouseID corresponds to the "day". May need to be careful as it's possible that the sessionID is not located in correct 'Day' subdirectory.

In [ ]:
# Figure 1
'''
Figure 1: Outbound and Inbound trajectories
    - Plotted for each mouse separately
    - For days 1-5
    - Plot per-day, i.e. 1 column per mouse, two subcolumns (outbound and inbound) per day.
    - Each row is one day.
    - Use `movemeent` package's `plot_centroid_trajectory` function to plot the trajectories (or use the `plot_path_grid` function from `data_conduit.qc` if you want to plot multiple trajectories in a grid layout).
'''