In [16]:
################################################################################
# Imports
################################################################################
    
import os
import re
from pathlib import Path
import harp
import pandas as pd
import numpy as np
import xarray as xr
import yaml
from collections.abc import Mapping

################################################################################

In [17]:
###########################

experiment_directory_path= './Bonsai_logs/2025-10-07T18-08-45'
harp_device_yaml_path= './device.yml'

device_list= ['Behavior0',
               'Behavior1',
               'Behavior2',
               'Behavior3',
               'Behavior4',
               'Behavior5',
]

device_IDs= {
    f'{device_list[0]}': 'ID_0',
    f'{device_list[1]}': 'ID_1',
    f'{device_list[2]}': 'ID_2',
    f'{device_list[3]}': 'ID_3',
    f'{device_list[4]}': 'ID_4',
    f'{device_list[5]}': 'ID_5',
}

device_registers_dict= {
    'Behavior0': ['8', '32', '34', '35', '44', '49', '50', '51', '78', '92'],
    'Behavior1': ['8', '32', '34', '35', '44', '49', '50', '51', '78', '92'],
    'Behavior2': ['8', '32', '34', '35', '44', '49', '50', '51', '78', '92'],
    'Behavior3': ['8', '32', '34', '35', '44', '49', '50', '51', '78', '92'],
    'Behavior4': ['8', '32', '34', '35', '44', '49', '50', '51', '78', '92'],
    'Behavior5': ['8', '32', '34', '35', '44', '49', '50', '51', '78', '92'],
}

Nosepoke_Activations_localIDs= ['DIPort0',
                                'DIPort1',
                                'DIPort2',
]

Nosepoke_LED_Activations_localIDs= ['DOPort0',
                                    'DOPort1',
                                    'DOPort2',
]

Nosepoke_Valve_Activations_localIDs= ['SupplyPort0',
                                      'SupplyPort1',
                                      'SupplyPort2',
]

Nosepoke_Reward_Release_localIDs= ['PulseSupplyPort0',
                                   'PulseSupplyPort1',
                                   'PulseSupplyPort2',
]

channel_list= ['Nosepoke0',
               'Nosepoke1',
               'Nosepoke2',
               'Nosepoke3',
               'Nosepoke4',
               'Nosepoke5',
               'Nosepoke6',
               'Nosepoke7',
               'Nosepoke8',
               'Nosepoke9',
               'Nosepoke10',
               'Nosepoke11',
               'Nosepoke12',
               'Nosepoke13',
               'Nosepoke14',
               'Nosepoke15',
               'Nosepoke16',
               'Nosepoke17',]


channel_type_localIDs= {
    'Activations': Nosepoke_Activations_localIDs,
    'LED_Activations': Nosepoke_LED_Activations_localIDs,
    'Valve_Activations': Nosepoke_Valve_Activations_localIDs,
    'Reward_Release': Nosepoke_Reward_Release_localIDs,
}

Activations_localID_register_dict= {
    'DIPort0': '32',
    'DIPort1': '32',
    'DIPort2': '32',
}
LED_Activations_localID_register_dict= {
    'DOPort0': '34',
    'DOPort1': '34',
    'DOPort2': '34',
}

Valve_Activations_localID_register_dict= {
    'SupplyPort0': '34',
    'SupplyPort1': '34',
    'SupplyPort2': '34',
}

Reward_Release_localID_register_dict= {
    'PulseSupplyPort0': '49',
    'PulseSupplyPort1': '50',
    'PulseSupplyPort2': '51',
}

channel_type_registerIDs= {
    'Activations': Activations_localID_register_dict,
    'LED_Activations': LED_Activations_localID_register_dict,
    'Valve_Activations': Valve_Activations_localID_register_dict,
    'Reward_Release': Reward_Release_localID_register_dict,
}


type_key= list(channel_type_localIDs.keys())[0]  # Type of channel to process (e.g., 'Activations'). Must be exact prefix from channel_type_localIDs keys

# Get the localIDs for this type_key
localIDs = channel_type_localIDs[type_key]  # ['DIPort0', 'DIPort1', 'DIPort2']


channel_ref_dict_b= {
    f'{channel_list[0]}':  (f'{device_list[0]}', f'{channel_type_registerIDs[type_key][localIDs[0]]}', f'{channel_type_localIDs[type_key][0]}'),
    f'{channel_list[1]}':  (f'{device_list[0]}', f'{channel_type_registerIDs[type_key][localIDs[1]]}', f'{channel_type_localIDs[type_key][1]}'),
    f'{channel_list[2]}':  (f'{device_list[0]}', f'{channel_type_registerIDs[type_key][localIDs[2]]}', f'{channel_type_localIDs[type_key][2]}'),

    f'{channel_list[3]}':  (f'{device_list[1]}', f'{channel_type_registerIDs[type_key][localIDs[0]]}',  f'{channel_type_localIDs[type_key][0]}'),
    f'{channel_list[4]}':  (f'{device_list[1]}', f'{channel_type_registerIDs[type_key][localIDs[1]]}',  f'{channel_type_localIDs[type_key][1]}'),
    f'{channel_list[5]}':  (f'{device_list[1]}', f'{channel_type_registerIDs[type_key][localIDs[2]]}',  f'{channel_type_localIDs[type_key][2]}'),

    f'{channel_list[6]}':  (f'{device_list[2]}', f'{channel_type_registerIDs[type_key][localIDs[0]]}',  f'{channel_type_localIDs[type_key][0]}'),
    f'{channel_list[7]}':  (f'{device_list[2]}', f'{channel_type_registerIDs[type_key][localIDs[1]]}',  f'{channel_type_localIDs[type_key][1]}'),
    f'{channel_list[8]}':  (f'{device_list[2]}', f'{channel_type_registerIDs[type_key][localIDs[2]]}',  f'{channel_type_localIDs[type_key][2]}'),

    f'{channel_list[9]}':  (f'{device_list[3]}', f'{channel_type_registerIDs[type_key][localIDs[0]]}', f'{channel_type_localIDs[type_key][0]}'),
    f'{channel_list[10]}': (f'{device_list[3]}', f'{channel_type_registerIDs[type_key][localIDs[1]]}', f'{channel_type_localIDs[type_key][1]}'),
    f'{channel_list[11]}': (f'{device_list[3]}', f'{channel_type_registerIDs[type_key][localIDs[2]]}', f'{channel_type_localIDs[type_key][2]}'),

    f'{channel_list[12]}': (f'{device_list[4]}', f'{channel_type_registerIDs[type_key][localIDs[0]]}', f'{channel_type_localIDs[type_key][0]}'),
    f'{channel_list[13]}': (f'{device_list[4]}', f'{channel_type_registerIDs[type_key][localIDs[1]]}', f'{channel_type_localIDs[type_key][1]}'),
    f'{channel_list[14]}': (f'{device_list[4]}', f'{channel_type_registerIDs[type_key][localIDs[2]]}', f'{channel_type_localIDs[type_key][2]}'),

    f'{channel_list[15]}': (f'{device_list[5]}', f'{channel_type_registerIDs[type_key][localIDs[0]]}', f'{channel_type_localIDs[type_key][0]}'),
    f'{channel_list[16]}': (f'{device_list[5]}', f'{channel_type_registerIDs[type_key][localIDs[1]]}', f'{channel_type_localIDs[type_key][1]}'),
    f'{channel_list[17]}': (f'{device_list[5]}', f'{channel_type_registerIDs[type_key][localIDs[2]]}', f'{channel_type_localIDs[type_key][2]}'),
}

channel_ref_dict_a= {
                f'{channel_list[0]}':  {'device': f'{device_list[0]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[0]]}', 'localID': f'{channel_type_localIDs[type_key][0]}'},
                f'{channel_list[1]}':  {'device': f'{device_list[0]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[1]]}', 'localID': f'{channel_type_localIDs[type_key][1]}'},
                f'{channel_list[2]}':  {'device': f'{device_list[0]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[2]]}', 'localID': f'{channel_type_localIDs[type_key][2]}'},

                f'{channel_list[3]}':  {'device': f'{device_list[1]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[0]]}', 'localID': f'{channel_type_localIDs[type_key][0]}'},
                f'{channel_list[4]}':  {'device': f'{device_list[1]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[1]]}', 'localID': f'{channel_type_localIDs[type_key][1]}'},
                f'{channel_list[5]}':  {'device': f'{device_list[1]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[2]]}', 'localID': f'{channel_type_localIDs[type_key][2]}'},

                f'{channel_list[6]}':  {'device': f'{device_list[2]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[0]]}', 'localID': f'{channel_type_localIDs[type_key][0]}'},
                f'{channel_list[7]}':  {'device': f'{device_list[2]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[1]]}', 'localID': f'{channel_type_localIDs[type_key][1]}'},
                f'{channel_list[8]}':  {'device': f'{device_list[2]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[2]]}', 'localID': f'{channel_type_localIDs[type_key][2]}'},

                f'{channel_list[9]}':  {'device': f'{device_list[3]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[0]]}', 'localID': f'{channel_type_localIDs[type_key][0]}'},
                f'{channel_list[10]}': {'device': f'{device_list[3]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[1]]}', 'localID': f'{channel_type_localIDs[type_key][1]}'},
                f'{channel_list[11]}': {'device': f'{device_list[3]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[2]]}', 'localID': f'{channel_type_localIDs[type_key][2]}'},

                f'{channel_list[12]}': {'device': f'{device_list[4]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[0]]}', 'localID': f'{channel_type_localIDs[type_key][0]}'},
                f'{channel_list[13]}': {'device': f'{device_list[4]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[1]]}', 'localID': f'{channel_type_localIDs[type_key][1]}'},
                f'{channel_list[14]}': {'device': f'{device_list[4]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[2]]}', 'localID': f'{channel_type_localIDs[type_key][2]}'},

                f'{channel_list[15]}': {'device': f'{device_list[5]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[0]]}', 'localID': f'{channel_type_localIDs[type_key][0]}'},
                f'{channel_list[16]}': {'device': f'{device_list[5]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[1]]}', 'localID': f'{channel_type_localIDs[type_key][1]}'},
                f'{channel_list[17]}': {'device': f'{device_list[5]}', 'register': f'{channel_type_registerIDs[type_key][localIDs[2]]}', 'localID': f'{channel_type_localIDs[type_key][2]}'},
            }
# channel_dict= {channel: (device, localID) for channel, (device, localID) in channel_ref_dict.items()}


device_type= 'Behavior'  # Type of device to process (e.g., 'Behavior'). Must be exact prefix 

channel_type_da_name= f'{type_key}'

In [18]:
channel_ref_dict= channel_ref_dict_a

In [19]:
######################################
from Refactor.HarpExtender.harp_extender_core import collect_device_dfs

experiment_directory_path= './Bonsai_logs/2025-10-07T18-08-45'
harp_device_yaml_path= './device.yml'


device_dfs_dict= collect_device_dfs(
    experiment_directory_path= experiment_directory_path,
    harp_device_yaml_path= harp_device_yaml_path,
    device_type= device_type,
    device_list= device_list,
    device_IDs= device_IDs,
    device_registers_dict= device_registers_dict,
    flatten= False,
    verbose= False,
    validate= False,
)

# display(device_dfs_dict)

############################################

# print structure of device_dfs_dict
for key in device_dfs_dict.keys():
    print(f'{key}: {type(device_dfs_dict[key])}')
    print('-' * 50)
    print(f'Subkeys: {device_dfs_dict[key].keys()}')
device_dfs_dict.keys()

Behavior0: <class 'dict'>
--------------------------------------------------
Subkeys: dict_keys(['8', '32', '34', '35', '44', '78', '92'])
Behavior1: <class 'dict'>
--------------------------------------------------
Subkeys: dict_keys(['8', '32', '34', '35', '44', '78', '92'])
Behavior2: <class 'dict'>
--------------------------------------------------
Subkeys: dict_keys(['8', '32', '34', '35', '44', '78', '92'])
Behavior3: <class 'dict'>
--------------------------------------------------
Subkeys: dict_keys(['8', '32', '34', '35', '44', '78', '92'])
Behavior4: <class 'dict'>
--------------------------------------------------
Subkeys: dict_keys(['8', '32', '34', '35', '44', '78', '92'])
Behavior5: <class 'dict'>
--------------------------------------------------
Subkeys: dict_keys(['8', '32', '34', '35', '44', '78', '92'])

dict_keys(['Behavior0', 'Behavior1', 'Behavior2', 'Behavior3', 'Behavior4', 'Behavior5'])

In [20]:
def dict_depth(d):
    return 1 + max(map(dict_depth, d.values()), default=0) if isinstance(d, dict) else 0


dict_depth(device_dfs_dict)

2

In [21]:
test= device_dfs_dict['Behavior0']['32']['DIPort0']

# Check type for test variable
print(type(test))
display(test)

<class 'pandas.core.series.Series'>

Time
105633.255072     True
105633.568576    False
105673.389504     True
105673.471680    False
106035.302304    False
106035.322752    False
106043.345664    False
106043.443744    False
Name: DIPort0, dtype: bool

In [22]:
virtual_map_b= channel_ref_dict_b

len(virtual_map_b['Nosepoke0'])

3

In [23]:
virtual_map_a= channel_ref_dict_a

#len(virtual_map['Nosepoke0'].keys())
len(virtual_map_a.keys())
virtual_coord_names = list(next(iter(virtual_map_a.values())).keys())
print(virtual_coord_names)

['device', 'register', 'localID']

In [24]:
virtual_map_b.items()
virtual_map_b.keys()

dict_keys(['Nosepoke0', 'Nosepoke1', 'Nosepoke2', 'Nosepoke3', 'Nosepoke4', 'Nosepoke5', 'Nosepoke6', 'Nosepoke7', 'Nosepoke8', 'Nosepoke9', 'Nosepoke10', 'Nosepoke11', 'Nosepoke12', 'Nosepoke13', 'Nosepoke14', 'Nosepoke15', 'Nosepoke16', 'Nosepoke17'])

In [25]:
virtual_map_a.items()
virtual_map_a.keys()

dict_keys(['Nosepoke0', 'Nosepoke1', 'Nosepoke2', 'Nosepoke3', 'Nosepoke4', 'Nosepoke5', 'Nosepoke6', 'Nosepoke7', 'Nosepoke8', 'Nosepoke9', 'Nosepoke10', 'Nosepoke11', 'Nosepoke12', 'Nosepoke13', 'Nosepoke14', 'Nosepoke15', 'Nosepoke16', 'Nosepoke17'])

In [26]:
dict_of= 'dicts'

dfs_dict= device_dfs_dict
if dict_of == 'tuples':
    virtual_map= virtual_map_b
elif dict_of == 'dicts':
    virtual_map= virtual_map_a
else:
    raise ValueError("dict_of must be 'tuples' or 'dicts'")

for global_coord, virtual_vals in virtual_map.items():
    print(f'global_coord: {global_coord}')
    print(f'virtual_coord: {virtual_vals}')

    if dict_of == 'tuples':
        device, register, localID = virtual_vals
    else:  # dicts
        device = virtual_vals['device']
        register = virtual_vals['register']
        localID = virtual_vals['localID']

    source_col = dfs_dict[device][register][localID]
    

    print(source_col)

global_coord: Nosepoke0
virtual_coord: {'device': 'Behavior0', 'register': '32', 'localID': 'DIPort0'}
Time
105633.255072     True
105633.568576    False
105673.389504     True
105673.471680    False
106035.302304    False
106035.322752    False
106043.345664    False
106043.443744    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke1
virtual_coord: {'device': 'Behavior0', 'register': '32', 'localID': 'DIPort1'}
Time
105633.255072    False
105633.568576    False
105673.389504    False
105673.471680    False
106035.302304     True
106035.322752    False
106043.345664    False
106043.443744    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke2
virtual_coord: {'device': 'Behavior0', 'register': '32', 'localID': 'DIPort2'}
Time
105633.255072    False
105633.568576    False
105673.389504    False
105673.471680    False
106035.302304    False
106035.322752    False
106043.345664     True
106043.443744    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke3
virtual_coord: {'device': 'Behavior1', 'register': '32', 'localID': 'DIPort0'}
Time
105556.648256    False
105556.684160    False
105556.701728    False
105556.788480    False
105697.369472    False
105697.573664    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke4
virtual_coord: {'device': 'Behavior1', 'register': '32', 'localID': 'DIPort1'}
Time
105556.648256    False
105556.684160    False
105556.701728    False
105556.788480    False
105697.369472     True
105697.573664    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke5
virtual_coord: {'device': 'Behavior1', 'register': '32', 'localID': 'DIPort2'}
Time
105556.648256     True
105556.684160    False
105556.701728     True
105556.788480    False
105697.369472    False
105697.573664    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke6
virtual_coord: {'device': 'Behavior2', 'register': '32', 'localID': 'DIPort0'}
Time
105136.375456    False
105136.670336    False
105164.753920    False
105164.971648    False
105790.470816    False
105790.591968    False
105790.608864    False
105790.743616    False
105792.610464    False
105792.791680    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke7
virtual_coord: {'device': 'Behavior2', 'register': '32', 'localID': 'DIPort1'}
Time
105136.375456     True
105136.670336    False
105164.753920     True
105164.971648    False
105790.470816    False
105790.591968    False
105790.608864    False
105790.743616    False
105792.610464    False
105792.791680    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke8
virtual_coord: {'device': 'Behavior2', 'register': '32', 'localID': 'DIPort2'}
Time
105136.375456    False
105136.670336    False
105164.753920    False
105164.971648    False
105790.470816     True
105790.591968    False
105790.608864     True
105790.743616    False
105792.610464     True
105792.791680    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke9
virtual_coord: {'device': 'Behavior3', 'register': '32', 'localID': 'DIPort0'}
Time
105451.754080    False
105451.893088    False
105766.290784     True
105766.619072    False
105782.499168     True
105782.553984    False
105786.995264     True
105787.055936    False
105798.357952    False
105798.541792    False
105799.842304    False
105799.906944    False
105908.860672    False
105909.231936    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke10
virtual_coord: {'device': 'Behavior3', 'register': '32', 'localID': 'DIPort1'}
Time
105451.754080    False
105451.893088    False
105766.290784    False
105766.619072    False
105782.499168    False
105782.553984    False
105786.995264    False
105787.055936    False
105798.357952     True
105798.541792    False
105799.842304     True
105799.906944    False
105908.860672    False
105909.231936    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke11
virtual_coord: {'device': 'Behavior3', 'register': '32', 'localID': 'DIPort2'}
Time
105451.754080     True
105451.893088    False
105766.290784    False
105766.619072    False
105782.499168    False
105782.553984    False
105786.995264    False
105787.055936    False
105798.357952    False
105798.541792    False
105799.842304    False
105799.906944    False
105908.860672     True
105909.231936    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke12
virtual_coord: {'device': 'Behavior4', 'register': '32', 'localID': 'DIPort0'}
Time
105850.543296     True
105850.566944    False
105850.584288     True
105850.825312    False
105883.071616    False
105883.147104    False
105924.389280    False
105924.718752    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke13
virtual_coord: {'device': 'Behavior4', 'register': '32', 'localID': 'DIPort1'}
Time
105850.543296    False
105850.566944    False
105850.584288    False
105850.825312    False
105883.071616     True
105883.147104    False
105924.389280    False
105924.718752    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke14
virtual_coord: {'device': 'Behavior4', 'register': '32', 'localID': 'DIPort2'}
Time
105850.543296    False
105850.566944    False
105850.584288    False
105850.825312    False
105883.071616    False
105883.147104    False
105924.389280     True
105924.718752    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke15
virtual_coord: {'device': 'Behavior5', 'register': '32', 'localID': 'DIPort0'}
Time
105539.656512     True
105539.954304    False
105860.990208     True
105861.171392    False
105935.863360     True
105935.956160    False
106094.423488    False
106094.554592    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke16
virtual_coord: {'device': 'Behavior5', 'register': '32', 'localID': 'DIPort1'}
Time
105539.656512    False
105539.954304    False
105860.990208    False
105861.171392    False
105935.863360    False
105935.956160    False
106094.423488     True
106094.554592    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke17
virtual_coord: {'device': 'Behavior5', 'register': '32', 'localID': 'DIPort2'}
Time
105539.656512    False
105539.954304    False
105860.990208    False
105861.171392    False
105935.863360    False
105935.956160    False
106094.423488    False
106094.554592    False
Name: DIPort2, dtype: bool

In [27]:
dict_of= 'tuples'

dfs_dict= device_dfs_dict
if dict_of == 'tuples':
    virtual_map= virtual_map_b
elif dict_of == 'dicts':
    virtual_map= virtual_map_a
else:
    raise ValueError("dict_of must be 'tuples' or 'dicts'")

for global_coord, virtual_vals in virtual_map.items():
    print(f'global_coord: {global_coord}')
    print(f'virtual_coord: {virtual_vals}')

    if dict_of == 'tuples':
        device, register, localID = virtual_vals
    else:  # dicts
        device = virtual_vals['device']
        register = virtual_vals['register']
        localID = virtual_vals['localID']

    source_col = dfs_dict[device][register][localID]
    

    print(source_col)

global_coord: Nosepoke0
virtual_coord: ('Behavior0', '32', 'DIPort0')
Time
105633.255072     True
105633.568576    False
105673.389504     True
105673.471680    False
106035.302304    False
106035.322752    False
106043.345664    False
106043.443744    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke1
virtual_coord: ('Behavior0', '32', 'DIPort1')
Time
105633.255072    False
105633.568576    False
105673.389504    False
105673.471680    False
106035.302304     True
106035.322752    False
106043.345664    False
106043.443744    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke2
virtual_coord: ('Behavior0', '32', 'DIPort2')
Time
105633.255072    False
105633.568576    False
105673.389504    False
105673.471680    False
106035.302304    False
106035.322752    False
106043.345664     True
106043.443744    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke3
virtual_coord: ('Behavior1', '32', 'DIPort0')
Time
105556.648256    False
105556.684160    False
105556.701728    False
105556.788480    False
105697.369472    False
105697.573664    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke4
virtual_coord: ('Behavior1', '32', 'DIPort1')
Time
105556.648256    False
105556.684160    False
105556.701728    False
105556.788480    False
105697.369472     True
105697.573664    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke5
virtual_coord: ('Behavior1', '32', 'DIPort2')
Time
105556.648256     True
105556.684160    False
105556.701728     True
105556.788480    False
105697.369472    False
105697.573664    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke6
virtual_coord: ('Behavior2', '32', 'DIPort0')
Time
105136.375456    False
105136.670336    False
105164.753920    False
105164.971648    False
105790.470816    False
105790.591968    False
105790.608864    False
105790.743616    False
105792.610464    False
105792.791680    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke7
virtual_coord: ('Behavior2', '32', 'DIPort1')
Time
105136.375456     True
105136.670336    False
105164.753920     True
105164.971648    False
105790.470816    False
105790.591968    False
105790.608864    False
105790.743616    False
105792.610464    False
105792.791680    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke8
virtual_coord: ('Behavior2', '32', 'DIPort2')
Time
105136.375456    False
105136.670336    False
105164.753920    False
105164.971648    False
105790.470816     True
105790.591968    False
105790.608864     True
105790.743616    False
105792.610464     True
105792.791680    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke9
virtual_coord: ('Behavior3', '32', 'DIPort0')
Time
105451.754080    False
105451.893088    False
105766.290784     True
105766.619072    False
105782.499168     True
105782.553984    False
105786.995264     True
105787.055936    False
105798.357952    False
105798.541792    False
105799.842304    False
105799.906944    False
105908.860672    False
105909.231936    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke10
virtual_coord: ('Behavior3', '32', 'DIPort1')
Time
105451.754080    False
105451.893088    False
105766.290784    False
105766.619072    False
105782.499168    False
105782.553984    False
105786.995264    False
105787.055936    False
105798.357952     True
105798.541792    False
105799.842304     True
105799.906944    False
105908.860672    False
105909.231936    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke11
virtual_coord: ('Behavior3', '32', 'DIPort2')
Time
105451.754080     True
105451.893088    False
105766.290784    False
105766.619072    False
105782.499168    False
105782.553984    False
105786.995264    False
105787.055936    False
105798.357952    False
105798.541792    False
105799.842304    False
105799.906944    False
105908.860672     True
105909.231936    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke12
virtual_coord: ('Behavior4', '32', 'DIPort0')
Time
105850.543296     True
105850.566944    False
105850.584288     True
105850.825312    False
105883.071616    False
105883.147104    False
105924.389280    False
105924.718752    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke13
virtual_coord: ('Behavior4', '32', 'DIPort1')
Time
105850.543296    False
105850.566944    False
105850.584288    False
105850.825312    False
105883.071616     True
105883.147104    False
105924.389280    False
105924.718752    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke14
virtual_coord: ('Behavior4', '32', 'DIPort2')
Time
105850.543296    False
105850.566944    False
105850.584288    False
105850.825312    False
105883.071616    False
105883.147104    False
105924.389280     True
105924.718752    False
Name: DIPort2, dtype: bool
global_coord: Nosepoke15
virtual_coord: ('Behavior5', '32', 'DIPort0')
Time
105539.656512     True
105539.954304    False
105860.990208     True
105861.171392    False
105935.863360     True
105935.956160    False
106094.423488    False
106094.554592    False
Name: DIPort0, dtype: bool
global_coord: Nosepoke16
virtual_coord: ('Behavior5', '32', 'DIPort1')
Time
105539.656512    False
105539.954304    False
105860.990208    False
105861.171392    False
105935.863360    False
105935.956160    False
106094.423488     True
106094.554592    False
Name: DIPort1, dtype: bool
global_coord: Nosepoke17
virtual_coord: ('Behavior5', '32', 'DIPort2')
Time
105539.656512    False
105539.954304    False
105860.990208    False
105861.171392    False
105935.863360    False
105935.956160    False
106094.423488    False
106094.554592    False
Name: DIPort2, dtype: bool

In [28]:
dfs_dict = device_dfs_dict

if dict_of == 'tuples':
    virtual_map = virtual_map_b
elif dict_of == 'dicts':
    virtual_map = virtual_map_a
else:
    raise ValueError("dict_of must be 'tuples' or 'dicts'")

for global_coord, virtual_vals in virtual_map.items():
    print(f'global_coord: {global_coord}')
    print(f'virtual_coord: {virtual_vals}')
    
    # Navigate nested dict
    current = dfs_dict
    
    if dict_of == 'tuples':
        for key in virtual_vals:
            current = current[key]
    else:  # dicts
        for key in virtual_vals.values():
            current = current[key]
    
    source_col = current
    display(source_col)
    if isinstance(source_col, pd.Series):
        print(f"Total times found: {source_col.sum() if source_col.dtype == bool else source_col.count()}")
        print(f"Total number of times (length): {len(source_col)}")
    elif isinstance(source_col, pd.DataFrame):
        print("Total times found (per column):")
        print(source_col.sum() if source_col.dtypes[0] == bool else source_col.count())
        print(f"Total number of times (rows): {len(source_col)}")
    else:
        print("Total times found: N/A")
        print("Total number of times: N/A")

global_coord: Nosepoke0
virtual_coord: ('Behavior0', '32', 'DIPort0')

Time
105633.255072     True
105633.568576    False
105673.389504     True
105673.471680    False
106035.302304    False
106035.322752    False
106043.345664    False
106043.443744    False
Name: DIPort0, dtype: bool

Total times found: 2
Total number of times (length): 8
global_coord: Nosepoke1
virtual_coord: ('Behavior0', '32', 'DIPort1')

Time
105633.255072    False
105633.568576    False
105673.389504    False
105673.471680    False
106035.302304     True
106035.322752    False
106043.345664    False
106043.443744    False
Name: DIPort1, dtype: bool

Total times found: 1
Total number of times (length): 8
global_coord: Nosepoke2
virtual_coord: ('Behavior0', '32', 'DIPort2')

Time
105633.255072    False
105633.568576    False
105673.389504    False
105673.471680    False
106035.302304    False
106035.322752    False
106043.345664     True
106043.443744    False
Name: DIPort2, dtype: bool

Total times found: 1
Total number of times (length): 8
global_coord: Nosepoke3
virtual_coord: ('Behavior1', '32', 'DIPort0')

Time
105556.648256    False
105556.684160    False
105556.701728    False
105556.788480    False
105697.369472    False
105697.573664    False
Name: DIPort0, dtype: bool

Total times found: 0
Total number of times (length): 6
global_coord: Nosepoke4
virtual_coord: ('Behavior1', '32', 'DIPort1')

Time
105556.648256    False
105556.684160    False
105556.701728    False
105556.788480    False
105697.369472     True
105697.573664    False
Name: DIPort1, dtype: bool

Total times found: 1
Total number of times (length): 6
global_coord: Nosepoke5
virtual_coord: ('Behavior1', '32', 'DIPort2')

Time
105556.648256     True
105556.684160    False
105556.701728     True
105556.788480    False
105697.369472    False
105697.573664    False
Name: DIPort2, dtype: bool

Total times found: 2
Total number of times (length): 6
global_coord: Nosepoke6
virtual_coord: ('Behavior2', '32', 'DIPort0')

Time
105136.375456    False
105136.670336    False
105164.753920    False
105164.971648    False
105790.470816    False
105790.591968    False
105790.608864    False
105790.743616    False
105792.610464    False
105792.791680    False
Name: DIPort0, dtype: bool

Total times found: 0
Total number of times (length): 10
global_coord: Nosepoke7
virtual_coord: ('Behavior2', '32', 'DIPort1')

Time
105136.375456     True
105136.670336    False
105164.753920     True
105164.971648    False
105790.470816    False
105790.591968    False
105790.608864    False
105790.743616    False
105792.610464    False
105792.791680    False
Name: DIPort1, dtype: bool

Total times found: 2
Total number of times (length): 10
global_coord: Nosepoke8
virtual_coord: ('Behavior2', '32', 'DIPort2')

Time
105136.375456    False
105136.670336    False
105164.753920    False
105164.971648    False
105790.470816     True
105790.591968    False
105790.608864     True
105790.743616    False
105792.610464     True
105792.791680    False
Name: DIPort2, dtype: bool

Total times found: 3
Total number of times (length): 10
global_coord: Nosepoke9
virtual_coord: ('Behavior3', '32', 'DIPort0')

Time
105451.754080    False
105451.893088    False
105766.290784     True
105766.619072    False
105782.499168     True
105782.553984    False
105786.995264     True
105787.055936    False
105798.357952    False
105798.541792    False
105799.842304    False
105799.906944    False
105908.860672    False
105909.231936    False
Name: DIPort0, dtype: bool

Total times found: 3
Total number of times (length): 14
global_coord: Nosepoke10
virtual_coord: ('Behavior3', '32', 'DIPort1')

Time
105451.754080    False
105451.893088    False
105766.290784    False
105766.619072    False
105782.499168    False
105782.553984    False
105786.995264    False
105787.055936    False
105798.357952     True
105798.541792    False
105799.842304     True
105799.906944    False
105908.860672    False
105909.231936    False
Name: DIPort1, dtype: bool

Total times found: 2
Total number of times (length): 14
global_coord: Nosepoke11
virtual_coord: ('Behavior3', '32', 'DIPort2')

Time
105451.754080     True
105451.893088    False
105766.290784    False
105766.619072    False
105782.499168    False
105782.553984    False
105786.995264    False
105787.055936    False
105798.357952    False
105798.541792    False
105799.842304    False
105799.906944    False
105908.860672     True
105909.231936    False
Name: DIPort2, dtype: bool

Total times found: 2
Total number of times (length): 14
global_coord: Nosepoke12
virtual_coord: ('Behavior4', '32', 'DIPort0')

Time
105850.543296     True
105850.566944    False
105850.584288     True
105850.825312    False
105883.071616    False
105883.147104    False
105924.389280    False
105924.718752    False
Name: DIPort0, dtype: bool

Total times found: 2
Total number of times (length): 8
global_coord: Nosepoke13
virtual_coord: ('Behavior4', '32', 'DIPort1')

Time
105850.543296    False
105850.566944    False
105850.584288    False
105850.825312    False
105883.071616     True
105883.147104    False
105924.389280    False
105924.718752    False
Name: DIPort1, dtype: bool

Total times found: 1
Total number of times (length): 8
global_coord: Nosepoke14
virtual_coord: ('Behavior4', '32', 'DIPort2')

Time
105850.543296    False
105850.566944    False
105850.584288    False
105850.825312    False
105883.071616    False
105883.147104    False
105924.389280     True
105924.718752    False
Name: DIPort2, dtype: bool

Total times found: 1
Total number of times (length): 8
global_coord: Nosepoke15
virtual_coord: ('Behavior5', '32', 'DIPort0')

Time
105539.656512     True
105539.954304    False
105860.990208     True
105861.171392    False
105935.863360     True
105935.956160    False
106094.423488    False
106094.554592    False
Name: DIPort0, dtype: bool

Total times found: 3
Total number of times (length): 8
global_coord: Nosepoke16
virtual_coord: ('Behavior5', '32', 'DIPort1')

Time
105539.656512    False
105539.954304    False
105860.990208    False
105861.171392    False
105935.863360    False
105935.956160    False
106094.423488     True
106094.554592    False
Name: DIPort1, dtype: bool

Total times found: 1
Total number of times (length): 8
global_coord: Nosepoke17
virtual_coord: ('Behavior5', '32', 'DIPort2')

Time
105539.656512    False
105539.954304    False
105860.990208    False
105861.171392    False
105935.863360    False
105935.956160    False
106094.423488    False
106094.554592    False
Name: DIPort2, dtype: bool

Total times found: 0
Total number of times (length): 8

In [29]:
from Refactor.LookupArrays.Lookup_Arrays_mod import construct_data_array
from Refactor.Timestamps.timestamps import collect_timestamps_nested_dict

times= collect_timestamps_nested_dict(
    dfs_dict= device_dfs_dict,
    data_key= type_key,
    peripheral_registerIDs= channel_type_registerIDs,
    devices= device_list,
    return_type= 'list',
    verbose= False
)

base_da = construct_data_array(virtual_map= virtual_map_b,
                                      global_coord_name= 'channel',
                                      virtual_coord_names= ['device', 'register','localID'],
                                      dict_of= 'tuples',
                                      times= times,
                                      name= f'{type_key}_data_array',
                                      test_values= True,
                                      verbose= True
                                        )


display(base_da.to_dataframe().unstack('channel').drop(columns=['device','register','localID']))

No da_attrs provided, using defaults.
No values provided, test_values is True. Creating test values DataArray with 54 timestamps and 18 unified coordinates.
Constructed test helper values array with shape: (54, 18)
Constructed DataArray "Activations_data_array" with dimensions: ('Time', 'channel') and shape: (54, 18)

                                          Activations_data_array  \
channel                                                Nosepoke0
Time
105136.375456  (Nosepoke0, device: Behavior0, register: 32, l...
105136.670336  (Nosepoke0, device: Behavior0, register: 32, l...
105164.753920  (Nosepoke0, device: Behavior0, register: 32, l...
105164.971648  (Nosepoke0, device: Behavior0, register: 32, l...
105451.754080  (Nosepoke0, device: Behavior0, register: 32, l...
105451.893088  (Nosepoke0, device: Behavior0, register: 32, l...
105539.656512  (Nosepoke0, device: Behavior0, register: 32, l...
105539.954304  (Nosepoke0, device: Behavior0, register: 32, l...
105556.648256  (Nosepoke0, device: Behavior0, register: 32, l...
105556.684160  (Nosepoke0, device: Behavior0, register: 32, l...
105556.701728  (Nosepoke0, device: Behavior0, register: 32, l...
105556.788480  (Nosepoke0, device: Behavior0, register: 32, l...
105633.255072  (Nosepoke0, device: Behavior0, register: 32, l...
105633.568576  (Nosepoke0, device: Behavior0, register: 32, l...
105673.389504  (Nosepoke0, device: Behavior0, register: 32, l...
105673.471680  (Nosepoke0, device: Behavior0, register: 32, l...
105697.369472  (Nosepoke0, device: Behavior0, register: 32, l...
105697.573664  (Nosepoke0, device: Behavior0, register: 32, l...
105766.290784  (Nosepoke0, device: Behavior0, register: 32, l...
105766.619072  (Nosepoke0, device: Behavior0, register: 32, l...
105782.499168  (Nosepoke0, device: Behavior0, register: 32, l...
105782.553984  (Nosepoke0, device: Behavior0, register: 32, l...
105786.995264  (Nosepoke0, device: Behavior0, register: 32, l...
105787.055936  (Nosepoke0, device: Behavior0, register: 32, l...
105790.470816  (Nosepoke0, device: Behavior0, register: 32, l...
105790.591968  (Nosepoke0, device: Behavior0, register: 32, l...
105790.608864  (Nosepoke0, device: Behavior0, register: 32, l...
105790.743616  (Nosepoke0, device: Behavior0, register: 32, l...
105792.610464  (Nosepoke0, device: Behavior0, register: 32, l...
105792.791680  (Nosepoke0, device: Behavior0, register: 32, l...
105798.357952  (Nosepoke0, device: Behavior0, register: 32, l...
105798.541792  (Nosepoke0, device: Behavior0, register: 32, l...
105799.842304  (Nosepoke0, device: Behavior0, register: 32, l...
105799.906944  (Nosepoke0, device: Behavior0, register: 32, l...
105850.543296  (Nosepoke0, device: Behavior0, register: 32, l...
105850.566944  (Nosepoke0, device: Behavior0, register: 32, l...
105850.584288  (Nosepoke0, device: Behavior0, register: 32, l...
105850.825312  (Nosepoke0, device: Behavior0, register: 32, l...
105860.990208  (Nosepoke0, device: Behavior0, register: 32, l...
105861.171392  (Nosepoke0, device: Behavior0, register: 32, l...
105883.071616  (Nosepoke0, device: Behavior0, register: 32, l...
105883.147104  (Nosepoke0, device: Behavior0, register: 32, l...
105908.860672  (Nosepoke0, device: Behavior0, register: 32, l...
105909.231936  (Nosepoke0, device: Behavior0, register: 32, l...
105924.389280  (Nosepoke0, device: Behavior0, register: 32, l...
105924.718752  (Nosepoke0, device: Behavior0, register: 32, l...
105935.863360  (Nosepoke0, device: Behavior0, register: 32, l...
105935.956160  (Nosepoke0, device: Behavior0, register: 32, l...
106035.302304  (Nosepoke0, device: Behavior0, register: 32, l...
106035.322752  (Nosepoke0, device: Behavior0, register: 32, l...
106043.345664  (Nosepoke0, device: Behavior0, register: 32, l...
106043.443744  (Nosepoke0, device: Behavior0, register: 32, l...
106094.423488  (Nosepoke0, device: Behavior0, register: 32, l...
106094.554592  (Nosepoke0, device: Behavior0, register: 32, l...

                                                                  \
channel                                                Nosepoke1
Time
105136.375456  (Nosepoke1, device: Behavior0, register: 32, l...
105136.670336  (Nosepoke1, device: Behavior0, register: 32, l...
105164.753920  (Nosepoke1, device: Behavior0, register: 32, l...
105164.971648  (Nosepoke1, device: Behavior0, register: 32, l...
105451.754080  (Nosepoke1, device: Behavior0, register: 32, l...
105451.893088  (Nosepoke1, device: Behavior0, register: 32, l...
105539.656512  (Nosepoke1, device: Behavior0, register: 32, l...
105539.954304  (Nosepoke1, device: Behavior0, register: 32, l...
105556.648256  (Nosepoke1, device: Behavior0, register: 32, l...
105556.684160  (Nosepoke1, device: Behavior0, register: 32, l...
105556.701728  (Nosepoke1, device: Behavior0, register: 32, l...
105556.788480  (Nosepoke1, device: Behavior0, register: 32, l...
105633.255072  (Nosepoke1, device: Behavior0, register: 32, l...
105633.568576  (Nosepoke1, device: Behavior0, register: 32, l...
105673.389504  (Nosepoke1, device: Behavior0, register: 32, l...
105673.471680  (Nosepoke1, device: Behavior0, register: 32, l...
105697.369472  (Nosepoke1, device: Behavior0, register: 32, l...
105697.573664  (Nosepoke1, device: Behavior0, register: 32, l...
105766.290784  (Nosepoke1, device: Behavior0, register: 32, l...
105766.619072  (Nosepoke1, device: Behavior0, register: 32, l...
105782.499168  (Nosepoke1, device: Behavior0, register: 32, l...
105782.553984  (Nosepoke1, device: Behavior0, register: 32, l...
105786.995264  (Nosepoke1, device: Behavior0, register: 32, l...
105787.055936  (Nosepoke1, device: Behavior0, register: 32, l...
105790.470816  (Nosepoke1, device: Behavior0, register: 32, l...
105790.591968  (Nosepoke1, device: Behavior0, register: 32, l...
105790.608864  (Nosepoke1, device: Behavior0, register: 32, l...
105790.743616  (Nosepoke1, device: Behavior0, register: 32, l...
105792.610464  (Nosepoke1, device: Behavior0, register: 32, l...
105792.791680  (Nosepoke1, device: Behavior0, register: 32, l...
105798.357952  (Nosepoke1, device: Behavior0, register: 32, l...
105798.541792  (Nosepoke1, device: Behavior0, register: 32, l...
105799.842304  (Nosepoke1, device: Behavior0, register: 32, l...
105799.906944  (Nosepoke1, device: Behavior0, register: 32, l...
105850.543296  (Nosepoke1, device: Behavior0, register: 32, l...
105850.566944  (Nosepoke1, device: Behavior0, register: 32, l...
105850.584288  (Nosepoke1, device: Behavior0, register: 32, l...
105850.825312  (Nosepoke1, device: Behavior0, register: 32, l...
105860.990208  (Nosepoke1, device: Behavior0, register: 32, l...
105861.171392  (Nosepoke1, device: Behavior0, register: 32, l...
105883.071616  (Nosepoke1, device: Behavior0, register: 32, l...
105883.147104  (Nosepoke1, device: Behavior0, register: 32, l...
105908.860672  (Nosepoke1, device: Behavior0, register: 32, l...
105909.231936  (Nosepoke1, device: Behavior0, register: 32, l...
105924.389280  (Nosepoke1, device: Behavior0, register: 32, l...
105924.718752  (Nosepoke1, device: Behavior0, register: 32, l...
105935.863360  (Nosepoke1, device: Behavior0, register: 32, l...
105935.956160  (Nosepoke1, device: Behavior0, register: 32, l...
106035.302304  (Nosepoke1, device: Behavior0, register: 32, l...
106035.322752  (Nosepoke1, device: Behavior0, register: 32, l...
106043.345664  (Nosepoke1, device: Behavior0, register: 32, l...
106043.443744  (Nosepoke1, device: Behavior0, register: 32, l...
106094.423488  (Nosepoke1, device: Behavior0, register: 32, l...
106094.554592  (Nosepoke1, device: Behavior0, register: 32, l...

                                                                  \
channel                                                Nosepoke2
Time
105136.375456  (Nosepoke2, device: Behavior0, register: 32, l...
105136.670336  (Nosepoke2, device: Behavior0, register: 32, l...
105164.753920  (Nosepoke2, device: Behavior0, register: 32, l...
105164.971648  (Nosepoke2, device: Behavior0, register: 32, l...
105451.754080  (Nosepoke2, device: Behavior0, register: 32, l...
105451.893088  (Nosepoke2, device: Behavior0, register: 32, l...
105539.656512  (Nosepoke2, device: Behavior0, register: 32, l...
105539.954304  (Nosepoke2, device: Behavior0, register: 32, l...
105556.648256  (Nosepoke2, device: Behavior0, register: 32, l...
105556.684160  (Nosepoke2, device: Behavior0, register: 32, l...
105556.701728  (Nosepoke2, device: Behavior0, register: 32, l...
105556.788480  (Nosepoke2, device: Behavior0, register: 32, l...
105633.255072  (Nosepoke2, device: Behavior0, register: 32, l...
105633.568576  (Nosepoke2, device: Behavior0, register: 32, l...
105673.389504  (Nosepoke2, device: Behavior0, register: 32, l...
105673.471680  (Nosepoke2, device: Behavior0, register: 32, l...
105697.369472  (Nosepoke2, device: Behavior0, register: 32, l...
105697.573664  (Nosepoke2, device: Behavior0, register: 32, l...
105766.290784  (Nosepoke2, device: Behavior0, register: 32, l...
105766.619072  (Nosepoke2, device: Behavior0, register: 32, l...
105782.499168  (Nosepoke2, device: Behavior0, register: 32, l...
105782.553984  (Nosepoke2, device: Behavior0, register: 32, l...
105786.995264  (Nosepoke2, device: Behavior0, register: 32, l...
105787.055936  (Nosepoke2, device: Behavior0, register: 32, l...
105790.470816  (Nosepoke2, device: Behavior0, register: 32, l...
105790.591968  (Nosepoke2, device: Behavior0, register: 32, l...
105790.608864  (Nosepoke2, device: Behavior0, register: 32, l...
105790.743616  (Nosepoke2, device: Behavior0, register: 32, l...
105792.610464  (Nosepoke2, device: Behavior0, register: 32, l...
105792.791680  (Nosepoke2, device: Behavior0, register: 32, l...
105798.357952  (Nosepoke2, device: Behavior0, register: 32, l...
105798.541792  (Nosepoke2, device: Behavior0, register: 32, l...
105799.842304  (Nosepoke2, device: Behavior0, register: 32, l...
105799.906944  (Nosepoke2, device: Behavior0, register: 32, l...
105850.543296  (Nosepoke2, device: Behavior0, register: 32, l...
105850.566944  (Nosepoke2, device: Behavior0, register: 32, l...
105850.584288  (Nosepoke2, device: Behavior0, register: 32, l...
105850.825312  (Nosepoke2, device: Behavior0, register: 32, l...
105860.990208  (Nosepoke2, device: Behavior0, register: 32, l...
105861.171392  (Nosepoke2, device: Behavior0, register: 32, l...
105883.071616  (Nosepoke2, device: Behavior0, register: 32, l...
105883.147104  (Nosepoke2, device: Behavior0, register: 32, l...
105908.860672  (Nosepoke2, device: Behavior0, register: 32, l...
105909.231936  (Nosepoke2, device: Behavior0, register: 32, l...
105924.389280  (Nosepoke2, device: Behavior0, register: 32, l...
105924.718752  (Nosepoke2, device: Behavior0, register: 32, l...
105935.863360  (Nosepoke2, device: Behavior0, register: 32, l...
105935.956160  (Nosepoke2, device: Behavior0, register: 32, l...
106035.302304  (Nosepoke2, device: Behavior0, register: 32, l...
106035.322752  (Nosepoke2, device: Behavior0, register: 32, l...
106043.345664  (Nosepoke2, device: Behavior0, register: 32, l...
106043.443744  (Nosepoke2, device: Behavior0, register: 32, l...
106094.423488  (Nosepoke2, device: Behavior0, register: 32, l...
106094.554592  (Nosepoke2, device: Behavior0, register: 32, l...

                                                                  \
channel                                                Nosepoke3
Time
105136.375456  (Nosepoke3, device: Behavior1, register: 32, l...
105136.670336  (Nosepoke3, device: Behavior1, register: 32, l...
105164.753920  (Nosepoke3, device: Behavior1, register: 32, l...
105164.971648  (Nosepoke3, device: Behavior1, register: 32, l...
105451.754080  (Nosepoke3, device: Behavior1, register: 32, l...
105451.893088  (Nosepoke3, device: Behavior1, register: 32, l...
105539.656512  (Nosepoke3, device: Behavior1, register: 32, l...
105539.954304  (Nosepoke3, device: Behavior1, register: 32, l...
105556.648256  (Nosepoke3, device: Behavior1, register: 32, l...
105556.684160  (Nosepoke3, device: Behavior1, register: 32, l...
105556.701728  (Nosepoke3, device: Behavior1, register: 32, l...
105556.788480  (Nosepoke3, device: Behavior1, register: 32, l...
105633.255072  (Nosepoke3, device: Behavior1, register: 32, l...
105633.568576  (Nosepoke3, device: Behavior1, register: 32, l...
105673.389504  (Nosepoke3, device: Behavior1, register: 32, l...
105673.471680  (Nosepoke3, device: Behavior1, register: 32, l...
105697.369472  (Nosepoke3, device: Behavior1, register: 32, l...
105697.573664  (Nosepoke3, device: Behavior1, register: 32, l...
105766.290784  (Nosepoke3, device: Behavior1, register: 32, l...
105766.619072  (Nosepoke3, device: Behavior1, register: 32, l...
105782.499168  (Nosepoke3, device: Behavior1, register: 32, l...
105782.553984  (Nosepoke3, device: Behavior1, register: 32, l...
105786.995264  (Nosepoke3, device: Behavior1, register: 32, l...
105787.055936  (Nosepoke3, device: Behavior1, register: 32, l...
105790.470816  (Nosepoke3, device: Behavior1, register: 32, l...
105790.591968  (Nosepoke3, device: Behavior1, register: 32, l...
105790.608864  (Nosepoke3, device: Behavior1, register: 32, l...
105790.743616  (Nosepoke3, device: Behavior1, register: 32, l...
105792.610464  (Nosepoke3, device: Behavior1, register: 32, l...
105792.791680  (Nosepoke3, device: Behavior1, register: 32, l...
105798.357952  (Nosepoke3, device: Behavior1, register: 32, l...
105798.541792  (Nosepoke3, device: Behavior1, register: 32, l...
105799.842304  (Nosepoke3, device: Behavior1, register: 32, l...
105799.906944  (Nosepoke3, device: Behavior1, register: 32, l...
105850.543296  (Nosepoke3, device: Behavior1, register: 32, l...
105850.566944  (Nosepoke3, device: Behavior1, register: 32, l...
105850.584288  (Nosepoke3, device: Behavior1, register: 32, l...
105850.825312  (Nosepoke3, device: Behavior1, register: 32, l...
105860.990208  (Nosepoke3, device: Behavior1, register: 32, l...
105861.171392  (Nosepoke3, device: Behavior1, register: 32, l...
105883.071616  (Nosepoke3, device: Behavior1, register: 32, l...
105883.147104  (Nosepoke3, device: Behavior1, register: 32, l...
105908.860672  (Nosepoke3, device: Behavior1, register: 32, l...
105909.231936  (Nosepoke3, device: Behavior1, register: 32, l...
105924.389280  (Nosepoke3, device: Behavior1, register: 32, l...
105924.718752  (Nosepoke3, device: Behavior1, register: 32, l...
105935.863360  (Nosepoke3, device: Behavior1, register: 32, l...
105935.956160  (Nosepoke3, device: Behavior1, register: 32, l...
106035.302304  (Nosepoke3, device: Behavior1, register: 32, l...
106035.322752  (Nosepoke3, device: Behavior1, register: 32, l...
106043.345664  (Nosepoke3, device: Behavior1, register: 32, l...
106043.443744  (Nosepoke3, device: Behavior1, register: 32, l...
106094.423488  (Nosepoke3, device: Behavior1, register: 32, l...
106094.554592  (Nosepoke3, device: Behavior1, register: 32, l...

                                                                  \
channel                                                Nosepoke4
Time
105136.375456  (Nosepoke4, device: Behavior1, register: 32, l...
105136.670336  (Nosepoke4, device: Behavior1, register: 32, l...
105164.753920  (Nosepoke4, device: Behavior1, register: 32, l...
105164.971648  (Nosepoke4, device: Behavior1, register: 32, l...
105451.754080  (Nosepoke4, device: Behavior1, register: 32, l...
105451.893088  (Nosepoke4, device: Behavior1, register: 32, l...
105539.656512  (Nosepoke4, device: Behavior1, register: 32, l...
105539.954304  (Nosepoke4, device: Behavior1, register: 32, l...
105556.648256  (Nosepoke4, device: Behavior1, register: 32, l...
105556.684160  (Nosepoke4, device: Behavior1, register: 32, l...
105556.701728  (Nosepoke4, device: Behavior1, register: 32, l...
105556.788480  (Nosepoke4, device: Behavior1, register: 32, l...
105633.255072  (Nosepoke4, device: Behavior1, register: 32, l...
105633.568576  (Nosepoke4, device: Behavior1, register: 32, l...
105673.389504  (Nosepoke4, device: Behavior1, register: 32, l...
105673.471680  (Nosepoke4, device: Behavior1, register: 32, l...
105697.369472  (Nosepoke4, device: Behavior1, register: 32, l...
105697.573664  (Nosepoke4, device: Behavior1, register: 32, l...
105766.290784  (Nosepoke4, device: Behavior1, register: 32, l...
105766.619072  (Nosepoke4, device: Behavior1, register: 32, l...
105782.499168  (Nosepoke4, device: Behavior1, register: 32, l...
105782.553984  (Nosepoke4, device: Behavior1, register: 32, l...
105786.995264  (Nosepoke4, device: Behavior1, register: 32, l...
105787.055936  (Nosepoke4, device: Behavior1, register: 32, l...
105790.470816  (Nosepoke4, device: Behavior1, register: 32, l...
105790.591968  (Nosepoke4, device: Behavior1, register: 32, l...
105790.608864  (Nosepoke4, device: Behavior1, register: 32, l...
105790.743616  (Nosepoke4, device: Behavior1, register: 32, l...
105792.610464  (Nosepoke4, device: Behavior1, register: 32, l...
105792.791680  (Nosepoke4, device: Behavior1, register: 32, l...
105798.357952  (Nosepoke4, device: Behavior1, register: 32, l...
105798.541792  (Nosepoke4, device: Behavior1, register: 32, l...
105799.842304  (Nosepoke4, device: Behavior1, register: 32, l...
105799.906944  (Nosepoke4, device: Behavior1, register: 32, l...
105850.543296  (Nosepoke4, device: Behavior1, register: 32, l...
105850.566944  (Nosepoke4, device: Behavior1, register: 32, l...
105850.584288  (Nosepoke4, device: Behavior1, register: 32, l...
105850.825312  (Nosepoke4, device: Behavior1, register: 32, l...
105860.990208  (Nosepoke4, device: Behavior1, register: 32, l...
105861.171392  (Nosepoke4, device: Behavior1, register: 32, l...
105883.071616  (Nosepoke4, device: Behavior1, register: 32, l...
105883.147104  (Nosepoke4, device: Behavior1, register: 32, l...
105908.860672  (Nosepoke4, device: Behavior1, register: 32, l...
105909.231936  (Nosepoke4, device: Behavior1, register: 32, l...
105924.389280  (Nosepoke4, device: Behavior1, register: 32, l...
105924.718752  (Nosepoke4, device: Behavior1, register: 32, l...
105935.863360  (Nosepoke4, device: Behavior1, register: 32, l...
105935.956160  (Nosepoke4, device: Behavior1, register: 32, l...
106035.302304  (Nosepoke4, device: Behavior1, register: 32, l...
106035.322752  (Nosepoke4, device: Behavior1, register: 32, l...
106043.345664  (Nosepoke4, device: Behavior1, register: 32, l...
106043.443744  (Nosepoke4, device: Behavior1, register: 32, l...
106094.423488  (Nosepoke4, device: Behavior1, register: 32, l...
106094.554592  (Nosepoke4, device: Behavior1, register: 32, l...

                                                                  \
channel                                                Nosepoke5
Time
105136.375456  (Nosepoke5, device: Behavior1, register: 32, l...
105136.670336  (Nosepoke5, device: Behavior1, register: 32, l...
105164.753920  (Nosepoke5, device: Behavior1, register: 32, l...
105164.971648  (Nosepoke5, device: Behavior1, register: 32, l...
105451.754080  (Nosepoke5, device: Behavior1, register: 32, l...
105451.893088  (Nosepoke5, device: Behavior1, register: 32, l...
105539.656512  (Nosepoke5, device: Behavior1, register: 32, l...
105539.954304  (Nosepoke5, device: Behavior1, register: 32, l...
105556.648256  (Nosepoke5, device: Behavior1, register: 32, l...
105556.684160  (Nosepoke5, device: Behavior1, register: 32, l...
105556.701728  (Nosepoke5, device: Behavior1, register: 32, l...
105556.788480  (Nosepoke5, device: Behavior1, register: 32, l...
105633.255072  (Nosepoke5, device: Behavior1, register: 32, l...
105633.568576  (Nosepoke5, device: Behavior1, register: 32, l...
105673.389504  (Nosepoke5, device: Behavior1, register: 32, l...
105673.471680  (Nosepoke5, device: Behavior1, register: 32, l...
105697.369472  (Nosepoke5, device: Behavior1, register: 32, l...
105697.573664  (Nosepoke5, device: Behavior1, register: 32, l...
105766.290784  (Nosepoke5, device: Behavior1, register: 32, l...
105766.619072  (Nosepoke5, device: Behavior1, register: 32, l...
105782.499168  (Nosepoke5, device: Behavior1, register: 32, l...
105782.553984  (Nosepoke5, device: Behavior1, register: 32, l...
105786.995264  (Nosepoke5, device: Behavior1, register: 32, l...
105787.055936  (Nosepoke5, device: Behavior1, register: 32, l...

In [30]:


def update_data_array(data_array: xr.DataArray = None,
                      virtual_map: dict = None,
                      dict_of: str = 'dicts',
                      dfs_dict: dict = None,
                      fill_value: any = np.nan,
                      verbose: bool = False
                    ) -> xr.DataArray:
    '''
    Updates DataArray with values from dfs_dict based on mapping provided in virtual_map. Format of dfs_dict and virtual_map should match, i.e. if dfs_dict is indexable as [global]: [virtual_1][virtual_2]



    '''

    #===== Validate Inputs
    if data_array is None:                          raise ValueError("data_array parameter must be provided and cannot be None.")
    if virtual_map is None:                         raise ValueError("virtual_map parameter must be provided and cannot be None.")
    if dict_of.lower() not in ('dicts', 'tuples'):  raise ValueError(f"dict_of must be either 'dicts' or 'tuples', got: {dict_of}")
    if dfs_dict is None:                            raise ValueError("dfs_dict parameter must be provided and cannot be None.")

    if verbose:
        print(f'Updating DataArray with shape {data_array.shape}')
        print(f'Virtual map format: {dict_of}')
        print(f'Number of global coordinates: {len(virtual_map)}')


    #===== Collect Dimensions 

    time_dim = [d for d in data_array.dims if d.lower() == 'time'][0]   # Identify time dimension
    global_dim = [d for d in data_array.dims if d.lower() != 'time'][0] # Identify global coordinate dimension

    da_time = data_array.get_index(time_dim)                            # Get time coordinate values
    
    # If fill_value provided, pre-fill entire array
    if fill_value is not None:
        data_array[:] = fill_value
    #===== Prebuild source columns dict to avoid redundant lookups in dfs_dict
    source_cols_dict = {}
    
    for global_coord, virtual_vals in virtual_map.items():
        try: 
            current = dfs_dict

            if dict_of == 'tuples':
                for key in virtual_vals:
                    current = current[key]
            else:  # dicts
                for key in virtual_vals.values():
                    current = current[key]
            
            # Store the source column in the dict
            source_cols_dict[global_coord] = current[global_coord] if isinstance(current, pd.DataFrame) else current
        except (KeyError, TypeError) as e:
            if verbose:
                print(f"Warning: Could not retrieve source column for global coordinate '{global_coord}' with virtual values {virtual_vals}. Error: {e}")
            source_cols_dict[global_coord] = pd.Series(fill_value, index=da_time)  # Fill with default value if retrieval fails
            

    # Catch case where no valid data to update
    if not source_cols_dict:
        return data_array

    #===== Bulk Update All DataArray Columns at once

    combined_df = pd.DataFrame(source_cols_dict)
    # Align combined_df with data_array time coordinate
    combined_df = combined_df.reindex(da_time, fill_value=fill_value if fill_value is not None else np.nan)

    # Single assignment to update entire DataArray
    valid_mask = combined_df.notna()
    
    for col in combined_df.columns:
        if verbose:
            print(f"Updating global coordinate '{col}' with {valid_mask[col].sum()} valid entries out of {len(valid_mask[col])} total.")
        mask = valid_mask[col]
        if mask.any():
            data_array.loc[{time_dim: da_time[mask], global_dim: col}] = combined_df.loc[mask, col].values
    return data_array

In [31]:
## # Test update_data_array function



updated_da= update_data_array(
    data_array= base_da ,
    virtual_map= virtual_map_b,
    dict_of= 'tuples',
    dfs_dict= device_dfs_dict,
    fill_value= False,
    verbose= True
)

display(updated_da.to_dataframe().unstack('channel').drop(columns=['device','register','localID']))

Updating DataArray with shape (54, 18)
Virtual map format: tuples
Number of global coordinates: 18
Updating global coordinate 'Nosepoke0' with 8 valid entries out of 54 total.
Updating global coordinate 'Nosepoke1' with 8 valid entries out of 54 total.
Updating global coordinate 'Nosepoke2' with 8 valid entries out of 54 total.
Updating global coordinate 'Nosepoke3' with 6 valid entries out of 54 total.
Updating global coordinate 'Nosepoke4' with 6 valid entries out of 54 total.
Updating global coordinate 'Nosepoke5' with 6 valid entries out of 54 total.
Updating global coordinate 'Nosepoke6' with 10 valid entries out of 54 total.
Updating global coordinate 'Nosepoke7' with 10 valid entries out of 54 total.
Updating global coordinate 'Nosepoke8' with 10 valid entries out of 54 total.
Updating global coordinate 'Nosepoke9' with 14 valid entries out of 54 total.
Updating global coordinate 'Nosepoke10' with 14 valid entries out of 54 total.
Updating global coordinate 'Nosepoke11' with 14 valid entries out of 54 total.
Updating global coordinate 'Nosepoke12' with 8 valid entries out of 54 total.
Updating global coordinate 'Nosepoke13' with 8 valid entries out of 54 total.
Updating global coordinate 'Nosepoke14' with 8 valid entries out of 54 total.
Updating global coordinate 'Nosepoke15' with 8 valid entries out of 54 total.
Updating global coordinate 'Nosepoke16' with 8 valid entries out of 54 total.
Updating global coordinate 'Nosepoke17' with 8 valid entries out of 54 total.

              Activations_data_array                                          \
channel                    Nosepoke0 Nosepoke1 Nosepoke2 Nosepoke3 Nosepoke4
Time
105136.375456                  False     False     False     False     False
105136.670336                  False     False     False     False     False
105164.753920                  False     False     False     False     False
105164.971648                  False     False     False     False     False
105451.754080                  False     False     False     False     False
105451.893088                  False     False     False     False     False
105539.656512                  False     False     False     False     False
105539.954304                  False     False     False     False     False
105556.648256                  False     False     False     False     False
105556.684160                  False     False     False     False     False
105556.701728                  False     False     False     False     False
105556.788480                  False     False     False     False     False
105633.255072                   True     False     False     False     False
105633.568576                  False     False     False     False     False
105673.389504                   True     False     False     False     False
105673.471680                  False     False     False     False     False
105697.369472                  False     False     False     False      True
105697.573664                  False     False     False     False     False
105766.290784                  False     False     False     False     False
105766.619072                  False     False     False     False     False
105782.499168                  False     False     False     False     False
105782.553984                  False     False     False     False     False
105786.995264                  False     False     False     False     False
105787.055936                  False     False     False     False     False
105790.470816                  False     False     False     False     False
105790.591968                  False     False     False     False     False
105790.608864                  False     False     False     False     False
105790.743616                  False     False     False     False     False
105792.610464                  False     False     False     False     False
105792.791680                  False     False     False     False     False
105798.357952                  False     False     False     False     False
105798.541792                  False     False     False     False     False
105799.842304                  False     False     False     False     False
105799.906944                  False     False     False     False     False
105850.543296                  False     False     False     False     False
105850.566944                  False     False     False     False     False
105850.584288                  False     False     False     False     False
105850.825312                  False     False     False     False     False
105860.990208                  False     False     False     False     False
105861.171392                  False     False     False     False     False
105883.071616                  False     False     False     False     False
105883.147104                  False     False     False     False     False
105908.860672                  False     False     False     False     False
105909.231936                  False     False     False     False     False
105924.389280                  False     False     False     False     False
105924.718752                  False     False     False     False     False
105935.863360                  False     False     False     False     False
105935.956160                  False     False     False     False     False
106035.302304                  False      True     False     False     False
106035.322752                  False     False     False     False     False
106043.345664                  False     False      True     False     False
106043.443744                  False     False     False     False     False
106094.423488                  False     False     False     False     False
106094.554592                  False     False     False     False     False

                                                                            \
channel       Nosepoke5 Nosepoke6 Nosepoke7 Nosepoke8 Nosepoke9 Nosepoke10
Time
105136.375456     False     False      True     False     False      False
105136.670336     False     False     False     False     False      False
105164.753920     False     False      True     False     False      False
105164.971648     False     False     False     False     False      False
105451.754080     False     False     False     False     False      False
105451.893088     False     False     False     False     False      False
105539.656512     False     False     False     False     False      False
105539.954304     False     False     False     False     False      False
105556.648256      True     False     False     False     False      False
105556.684160     False     False     False     False     False      False
105556.701728      True     False     False     False     False      False
105556.788480     False     False     False     False     False      False
105633.255072     False     False     False     False     False      False
105633.568576     False     False     False     False     False      False
105673.389504     False     False     False     False     False      False
105673.471680     False     False     False     False     False      False
105697.369472     False     False     False     False     False      False
105697.573664     False     False     False     False     False      False
105766.290784     False     False     False     False      True      False
105766.619072     False     False     False     False     False      False
105782.499168     False     False     False     False      True      False
105782.553984     False     False     False     False     False      False
105786.995264     False     False     False     False      True      False
105787.055936     False     False     False     False     False      False
105790.470816     False     False     False      True     False      False
105790.591968     False     False     False     False     False      False
105790.608864     False     False     False      True     False      False
105790.743616     False     False     False     False     False      False
105792.610464     False     False     False      True     False      False
105792.791680     False     False     False     False     False      False
105798.357952     False     False     False     False     False       True
105798.541792     False     False     False     False     False      False
105799.842304     False     False     False     False     False       True
105799.906944     False     False     False     False     False      False
105850.543296     False     False     False     False     False      False
105850.566944     False     False     False     False     False      False
105850.584288     False     False     False     False     False      False
105850.825312     False     False     False     False     False      False
105860.990208     False     False     False     False     False      False
105861.171392     False     False     False     False     False      False
105883.071616     False     False     False     False     False      False
105883.147104     False     False     False     False     False      False
105908.860672     False     False     False     False     False      False
105909.231936     False     False     False     False     False      False
105924.389280     False     False     False     False     False      False
105924.718752     False     False     False     False     False      False
105935.863360     False     False     False     False     False      False
105935.956160     False     False     False     False     False      False
106035.302304     False     False     False     False     False      False
106035.322752     False     False     False     False     False      False
106043.345664     False     False     False     False     False      False
106043.443744     False     False     False     False     False      False
106094.423488     False     False     False     False     False      False
106094.554592     False     False     False     False     False      False

                                                                      \
channel       Nosepoke11 Nosepoke12 Nosepoke13 Nosepoke14 Nosepoke15
Time
105136.375456      False      False      False      False      False
105136.670336      False      False      False      False      False
105164.753920      False      False      False      False      False
105164.971648      False      False      False      False      False
105451.754080       True      False      False      False      False
105451.893088      False      False      False      False      False
105539.656512      False      False      False      False       True
105539.954304      False      False      False      False      False
105556.648256      False      False      False      False      False
105556.684160      False      False      False      False      False
105556.701728      False      False      False      False      False
105556.788480      False      False      False      False      False
105633.255072      False      False      False      False      False
105633.568576      False      False      False      False      False
105673.389504      False      False      False      False      False
105673.471680      False      False      False      False      False
105697.369472      False      False      False      False      False
105697.573664      False      False      False      False      False
105766.290784      False      False      False      False      False
105766.619072      False      False      False      False      False
105782.499168      False      False      False      False      False
105782.553984      False      False      False      False      False
105786.995264      False      False      False      False      False
105787.055936      False      False      False      False      False
105790.470816      False      False      False      False      False
105790.591968      False      False      False      False      False
105790.608864      False      False      False      False      False
105790.743616      False      False      False      False      False
105792.610464      False      False      False      False      False
105792.791680      False      False      False      False      False
105798.357952      False      False      False      False      False
105798.541792      False      False      False      False      False
105799.842304      False      False      False      False      False
105799.906944      False      False      False      False      False
105850.543296      False       True      False      False      False
105850.566944      False      False      False      False      False
105850.584288      False       True      False      False      False
105850.825312      False      False      False      False      False
105860.990208      False      False      False      False       True
105861.171392      False      False      False      False      False
105883.071616      False      False       True      False      False
105883.147104      False      False      False      False      False
105908.860672       True      False      False      False      False
105909.231936      False      False      False      False      False
105924.389280      False      False      False       True      False
105924.718752      False      False      False      False      False
105935.863360      False      False      False      False       True
105935.956160      False      False      False      False      False
106035.302304      False      False      False      False      False
106035.322752      False      False      False      False      False
106043.345664      False      False      False      False      False
106043.443744      False      False      False      False      False
106094.423488      False      False      False      False      False
106094.554592      False      False      False      False      False


channel       Nosepoke16 Nosepoke17
Time
105136.375456      False      False
105136.670336      False      False
105164.753920      False      False
105164.971648      False      False
105451.754080      False      False
105451.893088      False      False
105539.656512      False      False
105539.954304      False      False
105556.648256      False      False
105556.684160      False      False
105556.701728      False      False
105556.788480      False      False
105633.255072      False      False
105633.568576      False      False
105673.389504      False      False
105673.471680      False      False
105697.369472      False      False
105697.573664      False      False
105766.290784      False      False
105766.619072      False      False
105782.499168      False      False
105782.553984      False      False
105786.995264      False      False
105787.055936      False      False
105790.470816      False      False
105790.591968      False      False
105790.608864      False      False
105790.743616      False      False
105792.610464      False      False
105792.791680      False      False
105798.357952      False      False
105798.541792      False      False
105799.842304      False      False
105799.906944      False      False
105850.543296      False      False
105850.566944      False      False
105850.584288      False      False
105850.825312      False      False
105860.990208      False      False
105861.171392      False      False
105883.071616      False      False
105883.147104      False      False
105908.860672      False      False
105909.231936      False      False
105924.389280      False      False
105924.718752      False      False
105935.863360      False      False
105935.956160      False      False
106035.302304      False      False
106035.322752      False      False
106043.345664      False      False
106043.443744      False      False
106094.423488       True      False
106094.554592      False      False